name: 'Simple Greeting Action'
description: 'A basic action to greet someone and generate a random number'
inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'World'
outputs:
  lucky-number:
    description: 'Your lucky number for the day'
    value: ${{ steps.number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Greet the user
      run: echo "Hello ${{ inputs.name }}!"
      shell: bash

    - name: Generate random number
      id: number-generator
      run: echo "random-number=$((1 + RANDOM % 100))" >> $GITHUB_OUTPUT
      shell: bash

    - name: Show farewell
      run: echo "Goodbye ${{ inputs.name }}! Your lucky number is ${{ steps.number-generator.outputs.random-number }}"
      shell: bash
