name: Matrix Application Test (Manual Trigger)



on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      extra_args:
        description: 'version tag (optional)'
        required: false
        type: string



jobs:
  test:
    name: "Test on ${{ matrix.os }} (Python ${{ matrix.python-version }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10"]
      fail-fast: false  # Don't stop other jobs if one fails



    steps:
      - uses: actions/checkout@v3



      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}



           - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



      - name: Run tests
        run: pytest ${{ github.event.inputs.extra_args }}



      - name: Notify on success
        if: success()
        run: echo "Tests passed on ${{ matrix.os }} (Python ${{ matrix.python-version }}) for ${{ github.event.inputs.environment }}"



  deploy:
    name: "Deploy to ${{ github.event.inputs.environment }}"
    needs: test  # Wait for all test jobs to finish
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'  # Only deploy if production is selected
    steps:
      - name: Log deployment
        run: echo "Deploying to ${{ github.event.inputs.environment }} with args: ${{ github.event.inputs.extra_args }}"
